### ISSUE TITLE
Issue with SAM

### ISSUE THREAD

**Issue by arjunrajlab** [Kitware/UPennContrast#638]
I have installed it on our Linux server. But every time someone tries to use the tool, it gives the error "Can't find WebGPU" or something like that. I'm not sure what's happening. In the console it seems fine, and if I do `navigator.gpu` in the console, there is an object, so I think WebGPU is enabled on these computers. They are M1 macs as compared to my M2 mac. Not sure if that makes a difference. Any quick suggestions @bruyeret ?

**Comment by bruyeret** [comment]
If the error is `Can't initialize SAM tool: WebGPU not available`, then it comes from the check `if (!("gpu" in navigator))`
On my Chrome, prompting `"gpu" in navigator` in the console returns `true` and it returns `false` on Firefox, as expected
This is weird to get this error if `navigator.gpu` is not `undefined`

I can simply this check and leave it fail when creating an inference session with WebGPU but it will have to download the model before showing the error

**Comment by arjunrajlab** [comment]
Is it possible the encoder/decoder files are in the wrong place? I noticed that the file structure had changed so I had to create the onnx-models/sam/vit_b directories. Perhaps I need to change permission?

**Comment by bruyeret** [comment]
The path to `encoder.onnx` and `decoder.onnx` should be `public/onnx-models/sam/vit_b` from the project root
Did you forget the `public` folder?

**Comment by arjunrajlab** [comment]
Hmm. I put it in public, so that's hopefully not the issue. Upon further looking, I see that `"gpu" in navigator` is actually false for the computers in the lab. Not sure what's going on, but perhaps those computers just don't support it. I'll try some more and let you know. But for now, I think the problem is on our side.

**Comment by arjunrajlab** [comment]
Is it possible to have it degrade back to using WASM/CPU if webGPU is not available? It is definitely slower, but at least it would enable it to work somewhat.

**Comment by arjunrajlab** [comment]
(Also, it is not a priority for now, I don't think.)

**Comment by bruyeret** [comment]
Do you confirm that `"gpu" in navigator` is false but `navigator.gpu` is an object?
Fallback to WASM shouldn't be hard to implement

**Comment by arjunrajlab** [comment]
navigator.gpu is undefined. Not sure why I was seeing it before, but now it is confirmed on multiple computers that it is not showing up. So that is definitely the problem. I'm Googling around now to see if this is a known issue on older computers.

**Comment by arjunrajlab** [comment]
Okay, this is really weird. When we connect ethernet, it says `"gpu" in navigator` is false, but when we disconnect from ethernet, it is true. Will do some more investigation.

**Comment by bruyeret** [comment]
It sounds like a browser bug or at least a very odd behavior, I will push something tomorrow to try to avoid it

**Comment by arjunrajlab** [comment]
Actually, I think this is the problem:
https://developer.chrome.com/docs/web-platform/webgpu/troubleshooting-tips

I think it is blocking webGPU because we serve through http and not https. I'll try to disable that security check first. Probably will take me until tomorrow. But I think that is the error.

**Comment by arjunrajlab** [comment]
I confirmed, the security thing is the issue. I disabled the security check and it works great!!

**Comment by bruyeret** [comment]
Oh yes I didn't think about it, a lot of recent browser features are only enabled in secure contexts!
I improved the CI, it should be soon ready to merge
I will make the PR
